/* USUÁRIO */

CREATE SEQUENCE public.tbusuario_usucodigo_seq;

CREATE TABLE public.TBUSUARIO (
    USUCODIGO BIGINT NOT NULL DEFAULT nextval('public.tbusuario_usucodigo_seq'),
    USUNOME VARCHAR(255) NOT NULL,
    USUEMAIL VARCHAR(255) NOT NULL,
    USUSENHA VARCHAR(255) NOT NULL,
    USUGESTOR BOOLEAN DEFAULT false NOT NULL,
    USUDATAHORAREGISTRO TIMESTAMP DEFAULT NOW()::TIMESTAMP NOT NULL,
    CONSTRAINT pk_tbusuario PRIMARY KEY (USUCODIGO)
);
COMMENT ON COLUMN public.TBUSUARIO.USUCODIGO IS 'Código do Usuário';
COMMENT ON COLUMN public.TBUSUARIO.USUNOME IS 'Nome do Usuário';
COMMENT ON COLUMN public.TBUSUARIO.USUEMAIL IS 'Email do Usuário';
COMMENT ON COLUMN public.TBUSUARIO.USUSENHA IS 'Senha do Usuário';
COMMENT ON COLUMN public.TBUSUARIO.USUGESTOR IS 'Define se o Usuário é Gestor (possui privilégios que um usuário normal não possui)';
COMMENT ON COLUMN public.TBUSUARIO.USUDATAHORAREGISTRO IS 'Data/Hora de Registro';

ALTER SEQUENCE public.tbusuario_usucodigo_seq OWNED BY public.TBUSUARIO.USUCODIGO;

/* CURSO */

CREATE SEQUENCE public.tbcurcodigo_curcodigo_seq;

CREATE TABLE public.TBCURSO (
    CURCODIGO BIGINT NOT NULL DEFAULT nextval('public.tbcurcodigo_curcodigo_seq'),
    CURNOME VARCHAR(100) NOT NULL,
    CURDESCRICAO VARCHAR(500) NOT NULL,
    CURIMAGEM VARCHAR NOT NULL,
    CURNOMEIMAGEM VARCHAR NOT NULL,
    CURTIPOIMAGEM VARCHAR(20) NOT NULL,
    CONSTRAINT pk_tbcurso PRIMARY KEY (CURCODIGO)
);
COMMENT ON COLUMN public.TBCURSO.CURCODIGO IS 'Código do Curso';
COMMENT ON COLUMN public.TBCURSO.CURNOME IS 'Nome do Curso';
COMMENT ON COLUMN public.TBCURSO.CURDESCRICAO IS 'Descrição do Curso';
COMMENT ON COLUMN public.TBCURSO.CURIMAGEM IS 'Imagem do Curso';
COMMENT ON COLUMN public.TBCURSO.CURNOMEIMAGEM IS 'Nome da Imagem';
COMMENT ON COLUMN public.TBCURSO.CURTIPOIMAGEM IS 'Tipo da Imagem';

ALTER SEQUENCE public.tbcurcodigo_curcodigo_seq OWNED BY public.TBCURSO.CURCODIGO;

/* VÍDEO */

CREATE SEQUENCE public.tbvideo_vidcodigo_seq;

CREATE TABLE public.TBVIDEO (
    VIDCODIGO BIGINT NOT NULL DEFAULT nextval('public.tbvideo_vidcodigo_seq'),
    CURCODIGO BIGINT NOT NULL,
    VIDTITULO VARCHAR(255) NOT NULL,
    VIDDESCRICAO VARCHAR NOT NULL,
    VIDCAMINHO VARCHAR(255) NOT NULL,
    VIDDURACAO REAL NOT NULL,
    VIDDATAHORAREGISTRO TIMESTAMP DEFAULT now()::timestamp NOT NULL,
    CONSTRAINT pk_tbvideo PRIMARY KEY (VIDCODIGO, CURCODIGO)
);
COMMENT ON COLUMN public.TBVIDEO.VIDTITULO IS 'Título do Vídeo';
COMMENT ON COLUMN public.TBVIDEO.VIDDESCRICAO IS 'Descrição do Vídeo';
COMMENT ON COLUMN public.TBVIDEO.VIDCAMINHO IS 'Caminho do Vídeo';
COMMENT ON COLUMN public.TBVIDEO.VIDDURACAO IS 'Duração do Vídeo em Segundos';
COMMENT ON COLUMN public.TBVIDEO.VIDDATAHORAREGISTRO IS 'Data/Hora de Registro';

ALTER SEQUENCE public.tbvideo_vidcodigo_seq OWNED BY public.TBVIDEO.VIDCODIGO;

ALTER TABLE public.TBVIDEO ADD CONSTRAINT tbcurso_tbvideo_fk FOREIGN KEY (CURCODIGO) REFERENCES public.TBCURSO (CURCODIGO)
ON DELETE CASCADE ON UPDATE NO ACTION NOT DEFERRABLE;

/* AVALIAÇÃO */

CREATE SEQUENCE public.tbavaliacao_avacodigo_seq;

CREATE TABLE public.TBAVALIACAO (
    AVACODIGO BIGINT NOT NULL DEFAULT nextval('public.tbavaliacao_avacodigo_seq'),
    VIDCODIGO BIGINT NOT NULL,
    CURCODIGO BIGINT NOT NULL,
    AVAQUESTAO VARCHAR NOT NULL,
    CONSTRAINT pk_tbavaliacao PRIMARY KEY (AVACODIGO, VIDCODIGO, CURCODIGO)
);
COMMENT ON COLUMN public.TBAVALIACAO.AVACODIGO IS 'Código da Avaliação';
COMMENT ON COLUMN public.TBAVALIACAO.VIDCODIGO IS 'Código do Vídeo';
COMMENT ON COLUMN public.TBAVALIACAO.CURCODIGO IS 'Código do Curso';

ALTER SEQUENCE public.tbavaliacao_avacodigo_seq OWNED BY public.TBAVALIACAO.AVACODIGO;

ALTER TABLE public.TBAVALIACAO ADD CONSTRAINT tbvideo_tbavaliacao_fk FOREIGN KEY (VIDCODIGO, CURCODIGO) REFERENCES public.TBVIDEO (VIDCODIGO, CURCODIGO)
ON DELETE CASCADE ON UPDATE NO ACTION NOT DEFERRABLE;

/* ALTERNATIVA */

CREATE SEQUENCE public.tbalternativa_altcodigo_seq;

CREATE TABLE public.TBALTERNATIVA (
    ALTCODIGO BIGINT NOT NULL DEFAULT nextval('public.tbalternativa_altcodigo_seq'),
    AVACODIGO BIGINT NOT NULL,
    VIDCODIGO BIGINT NOT NULL,
    CURCODIGO BIGINT NOT NULL,
    ALTDESCRICAO VARCHAR(255) NOT NULL,
    ALTCORRETA BOOLEAN DEFAULT false NOT NULL,
    CONSTRAINT pk_tbalternativa PRIMARY KEY (ALTCODIGO, AVACODIGO, VIDCODIGO, CURCODIGO)
);
COMMENT ON COLUMN public.TBALTERNATIVA.ALTCODIGO IS 'Código da Alternativa';
COMMENT ON COLUMN public.TBALTERNATIVA.AVACODIGO IS 'Código da Avaliação';
COMMENT ON COLUMN public.TBALTERNATIVA.VIDCODIGO IS 'Código do Vídeo';
COMMENT ON COLUMN public.TBALTERNATIVA.CURCODIGO IS 'Código do Curso';
COMMENT ON COLUMN public.TBALTERNATIVA.ALTDESCRICAO IS 'Descrição da Alternativa';
COMMENT ON COLUMN public.TBALTERNATIVA.ALTCORRETA IS 'Define a alternativa correta';

ALTER SEQUENCE public.tbalternativa_altcodigo_seq OWNED BY public.TBALTERNATIVA.ALTCODIGO;

ALTER TABLE public.TBALTERNATIVA ADD CONSTRAINT tbavaliacao_tbalternativa_fk FOREIGN KEY (VIDCODIGO, AVACODIGO, CURCODIGO) REFERENCES public.TBAVALIACAO (VIDCODIGO, AVACODIGO, CURCODIGO)
ON DELETE CASCADE ON UPDATE NO ACTION NOT DEFERRABLE;

/* RESPOSTA */

CREATE TABLE public.TBRESPOSTA (
    USUCODIGO BIGINT NOT NULL,
    CURCODIGO BIGINT NOT NULL,
    VIDCODIGO BIGINT NOT NULL,
    AVACODIGO BIGINT NOT NULL,
    ALTCODIGO BIGINT NOT NULL,
    CONSTRAINT pk_tbresposta PRIMARY KEY (USUCODIGO, CURCODIGO, VIDCODIGO, AVACODIGO, ALTCODIGO)
);
COMMENT ON COLUMN public.TBRESPOSTA.USUCODIGO IS 'Código do Usuário';
COMMENT ON COLUMN public.TBRESPOSTA.CURCODIGO IS 'Código do Curso';
COMMENT ON COLUMN public.TBRESPOSTA.VIDCODIGO IS 'Código do Vídeo';
COMMENT ON COLUMN public.TBRESPOSTA.AVACODIGO IS 'Código da Avaliação';
COMMENT ON COLUMN public.TBRESPOSTA.ALTCODIGO IS 'Código da Alternativa';

ALTER TABLE public.TBRESPOSTA ADD CONSTRAINT tbusuario_tbresposta_fk FOREIGN KEY (USUCODIGO) REFERENCES public.TBUSUARIO (USUCODIGO)
ON DELETE NO ACTION ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE public.TBRESPOSTA ADD CONSTRAINT tbalternativa_tbresposta_fk FOREIGN KEY (ALTCODIGO, AVACODIGO, VIDCODIGO, CURCODIGO) REFERENCES public.TBALTERNATIVA (ALTCODIGO, AVACODIGO, VIDCODIGO, CURCODIGO)
ON DELETE NO ACTION ON UPDATE NO ACTION NOT DEFERRABLE;